#!/bin/sh
#
# runtests: run test binaries

set -eu

COL_GREEN="\033[32m"
COL_RED="\033[31m"
COL_RST="\033[m"

CUR=$PWD
cd "$(dirname "$0")" >/dev/null 2>&1
TOOLS=$PWD
cd "$CUR" >/dev/null 2>&1

usage () {
    echo "Usage: runtests [testbin [testbin [...]]]"
    echo
    echo "Runs all passed test binaries, filtering output for readability."
}

run_all () {
    local out=
    local fail=0
    for bin in "$@"; do
        sep
        set +e
        out=$(./"$bin")
        if [ "$?" -ne "0" ]; then
            fail=1
        fi
        set -e
        echo "$out" | "$TOOLS"/greenify
    done
    sep
    if [ "$fail" -ne "0" ]; then
        colecho $COL_RED "Some tests failed. See above for details."
        exit 1
    else
        colecho $COL_GREEN "All tests passed! Sing a song to celebrate!"
    fi
}

colecho () {
    local col=$1
    shift
    echo "${col}${@}${COL_RST}"
}

sep () {
    echo ----
}

if [ "$#" -eq "0" ] || [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    usage >&2
    exit 1
fi

run_all "$@"
